## Emacs: -*- coding: utf-8; fill-column: 62; comment-column: 27; -*-
##
## Copyright (C) 2017 Vincent Goulet
##
## This file is part of the project "Computational actuarial
## science with R - IME 2017 Workshop"
## http://github.com/vigou3/ime-2017-workshop-computational-actuarial-science-r
##
## This work is licensed under a Creative Commons
## Attribution-ShareAlike 4.0 International License.
## http://creativecommons.org/licenses/by-sa/4.0/


###
### EXAMPLES OF R (APPARENTLY) GETTING ITS MATH WRONG
###

## The examples below are all taken from genuine messages sent
## to the r-help mailing list
## (https://stat.ethz.ch/mailman/listinfo/r-help/) claiming R
## can compute correctly.

## Addition and subtraction operators not respecting basic
## rules of arithmetic.
1.2 + 1.4 + 2.8            # 5.4
1.2 + 1.4 + 2.8 == 5.4     # no?!?
2.8 + 1.2 + 1.4            # still 5.4
2.8 + 1.2 + 1.4 == 5.4     # so addition non commutative?
2.6 - 1.4 - 1.2            # should be 0
2.6 - 1.5 - 1.1            # correct here

## Division sometimes giving wrong results.
0.2/0.1 == 2               # ok
(1.2 - 1.0)/0.1 == 2       # should be equivalent
0.3/0.1 == 3               # worked with 0.2!

## Distance between 3.2 and 3.15 larger than between 3.10 and
## 3.15.
3.2 - 3.15 > 0.05          # larger than 0.05...
3.15 - 3.1 < 0.05          # and now smaller than 0.05

## Wrong values in sequences generated by 'seq' using
## successive additions or subtractions.
(a <- seq(0.9, 0.95, by = 0.01))
a == 0.94                  # 0.94 is not in the vector!
(b <- c(0.90, 0.91, 0.92, 0.93, 0.94, 0.95))
b == 0.94                  # this time, it is!
a - b                      # note 5th element
